#![allow(unsafe_op_in_unsafe_fn)]
use std::ffi::c_char;

// Bindings for libsystemd generated by bindgen at compile time.
// The build script reads the system headers from `/usr/include/systemd`.
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

pub extern "C" fn systemd_version() -> *const c_char {
    return b"257.5".as_ptr() as *const c_char
}

